### ISSUE TITLE
Associative Array in QueryFilter constructor

### ISSUE THREAD

**Issue by giannicic** [tiagomichaelsousa/LaravelFilters#13]
Hi, would you accept a PR that allow the `QueryFilter ` to be istantiated also with a plain associative array?
In this way it would be possible to use filters also outside of the Http context (Eg. in commands)

Se we could use it like the following:

`$results = Model::filter(new Filter(['field1' => $value1, 'field2' => $value2]))->get();`

**Comment by devoncmather** [comment]
Dealing with the request object can sometimes be cumbersome, so I would appreciate this feature 👍🏻

**Comment by tiagomichaelsousa** [comment]
Looks promising @giannicic 😎 
Feel free to make the PR and thank you for your time in finding ways to improve the package🙏🚀

**Comment by giannicic** [comment]
Thanks @tiagomichaelsousa 
Just created the PR.

**Comment by tiagomichaelsousa** [comment]
[closed with #14](https://github.com/tiagomichaelsousa/LaravelFilters/pull/14)
