### ISSUE TITLE
Passing null values in request, gives odd results

### ISSUE THREAD

**Issue by devonmather** [tiagomichaelsousa/LaravelFilters#9]
I have a filter that I want to pass a default value to. I can't guarantee the user will pass that value by default from the API. So I have extended the filters method so I can append the value to the request if it's missing.

```
class CategoryFilters extends QueryFilters
{
    public function filters()
    {
        $filters = $this->request->all();
		
        if(!isset($filters['parent_category'])) {
            $filters['parent_category'] = null;
        }

        return $filters;
    }

    public function parent_category($id) {
        return $this->builder->where('parent_category_id', $id);
    }
}
```

However when null is passed for some reason it calls the function without a parameter, thus triggering an error. I'm not sure why the package explicitly calls a separate method if null exists? 

```
abstract class QueryFilters
{
    public function apply(Builder $builder)
    {
        $this->builder = $builder;

        foreach ($this->filters() as $filter => $value) {
            if (! method_exists($this, $filter)) {
                continue;
            }

            // strlen($value) ? $this->$filter($value) : $this->$filter();
           $this->$filter($value); // Seems like the sensible default?
        }

        return $this->builder;
    }
```

Let me know if there's something I'm missing, happy to make a PR if need be ✌🏻

**Comment by tiagomichaelsousa** [comment]
Hi @devonmather 🙂

I have a possible solution for you, but I don't know if it will work, it depends on your business logic but it will probably help.

If I understood your issue, you want to send in the URL something like  `/api/categories?parent_category` and add a default value to the `parent_category` querystring, right?

So, what you can do its just set a default value for the `$id` parameter in the `parent_category` function.

```php
/**
 * Find by parent category id.
 *
 * @param  int  $id
 * @return Builder
 */
public function parent_category($id = 4)
{
    return $this->builder->where('parent_id', $id);
}
```

With that, you can just send the request as above and if it doesn't receive any value it will fallback to the id 4.

The cool thing is, if you make the request with a value, like request `/api/categories?parent_category=5` it will not fallback the value to 4 and it will use what you sent in the query string 🙂

Other thing, and that's a bonus 😃 if you want to filter by multiple `parent_id` values you can send the request like `/api/categories?parent_category=2,3,4,5` and explode the parameter in the filter function.

```php
/**
 * Find by multiple parent category id.
 *
 * @param  int  $id
 * @return Builder
 */
public function parent_category($ids = 4)
{
    return $this->builder->whereIn('parent_id', explode(',', $ids));
}
```

With this approach, you don't need to override/extend a custom QueryFilter class 🚀

Hope it helps!

Thank you 🚀
Tiago Sousa

**Comment by devonmather** [comment]
Hi Tiago, 

Thanks for the detailed reply! I'm not sure if it really addressed my issue though. Although I do like the bit about exploding the ID's and using `whereIn()`

My issue is with the following line from the QueryFilters class that I commented out above. I think with your suggestion the problem would still exist. See below;

```
strlen($value) ? $this->$filter($value) : $this->$filter();
```

What appears to be happening is if there is no $value present it calls the method without a parameter. Which then causes an error as the method signature no longer matches the method.

I believe the line needs to be amended to the following? So as to allow the default value of `4` as per your example to be set by the method.
```
$this->$filter($value);
```

I like the package by the way ✌🏻

Warm regards,
Devon Mather

**Comment by tiagomichaelsousa** [comment]
Hi @devonmather 🙂 

I just took the time to look deeper and it looks like you are right!

Feel free to submit a PR 🚀 I will add you as a contributor after that 🎉

Thank you,
Tiago Sousa
